[package]
name = "aoc-2023"
version = "0.1.0"
authors = ["Zan Baldwin <hello@zanbaldwin.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-common = { path = "../common" }
humanize-duration = "0.0.6"
nom = "7.1.3"

[dev-dependencies]
rstest = "0.23"
rstest_reuse = "0.7"
