name: 'Rust 2023'

on:
  push:
    branches: [ 'main' ]
    paths:
    - '2023/**'
    - '.github/workflows/**'
  pull_request:
    branches: [ 'main' ]
    paths:
    - '2023/**'
    - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: 'always'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'
    - name: 'Build'
      run: 'cargo build --verbose'
      working-directory: '2023/'
    - name: 'Test'
      run: 'cargo test --verbose'
      working-directory: '2023/'
